[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "OmegaQMC"
version = "0.2.0"
description = "QMC with fragment-wise correlated sampling and cavity coupling"
authors = [
    {name = "Soohaeng Yoo Willow", email = "sy7willow@gmail.com"},
    {name = "Chang Woo Myung", email = "cwmyung@skku.edu"},
    {name = "David ChangMo Yang", email = "dcyang@skku.edu"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "pyscf>=2.10.0",
    "jax>=0.8",
    "pytest",
    "optax"
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

[project.optional-dependencies]
bse = ["basis-set-exchange"]

