[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vmc-mlsw"
version = "0.1.0"
description = "Variational Monte Carlo with machine-learned space warping"
authors = [
    {name = "Soohaeng Yoo Willow", email = "sy7willow@gmail.com"},
    {name = "Chang Woo Myung", email = "cwmyung@skku.edu"},
    {name = "David ChangMo Yang", email = "dcyang@skku.edu"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "pyscf>=2.0.0",
    "jax>=0.6",
    "optax"
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

