"""Vertical IP/EA benchmark for aromatic acenes -- extra rows for
Tables I and II of paper/main.tex (benzene, naphthalene, anthracene).

Same protocol as ``run_qed_ipea_benchmark.py`` but restricted to the
columns the current paper keeps:

    Koopmans (-eps_HOMO / -eps_LUMO of QED-HF),  Delta-QED-HF,
    G0W0 (non-linear one-shot),  evGW,  Delta-QED-CCSD

for each molecule coupled to a single z-polarized cavity mode
(omega_cav = 0.415668 Ha = 11.31 eV, the same water-resonant frequency
used for the whole table) at lambda = 0 and 0.05, in cc-pVDZ.

    IP = E0(N-1) - E0(N),   EA = E0(N) - E0(N+1)

with every energy a ground state of the same Pauli-Fierz Hamiltonian
(vertical: same geometry; molecular centroid at the origin; the doublet
cation and anion use a QED-UHF reference). No linG0W0 / SOSEX / FCI
(those were removed from the paper).

Geometry: idealized planar acenes on a honeycomb lattice, C-C = 1.40 A,
C-H = 1.09 A, generated by ``acene(n_rings)``. The molecular plane is
the x-z plane with the long (spine) axis along x and the SHORT in-plane
axis along z, so the z-polarized cavity couples to the short-axis
(bright 1La-type) transitions -- the acene analogue of the z-axis
convention used for the hydrides. Replace ``GEOMETRIES`` with optimized
Cartesian coordinates if preferred (keep the same orientation).

=====================================================================
MEMORY / RUNTIME WARNING.
Both the QED-GW and the Delta-QED-CCSD kernels build the *dense* nso^4
spin-orbital 2-electron integral tensor (nso = 2 * n_AO), and QED-GW
additionally dense-diagonalizes the photon-augmented RPA matrix of
dimension ~2*Nov (Nov = spin-orbital occ*vir). The nso^4 tensor is the
wall -- it dominates and does not fit small-RAM machines. Rough per-run
peak working set:

                       nso   nso^4 tensor   +RPA     total
    benzene  cc-pVDZ   228     ~22 GB        ~2 GB    ~24 GB
    naphtha. cc-pVDZ   360    ~134 GB       ~13 GB   ~147 GB
    anthrac. cc-pVDZ   492    ~469 GB       ~45 GB   ~514 GB
    benzene  6-31G     132     ~2.4 GB       ~2 GB    ~4 GB
    naphtha. sto-3g    116     ~1.5 GB       ~1 GB    ~3 GB
    benzene  sto-3g     72     ~0.2 GB      ~0.2 GB   ~0.4 GB

The paper protocol is cc-pVDZ on a 32-128 GB machine. On a small-RAM box
that is impossible, so this script (a) defaults to a small BASIS and
(b) estimates every molecule's peak working set with ``peak_gb`` and
*skips* any that would exceed a fraction of the physical RAM
(MEM_BUDGET_GB), writing the rows it can compute and logging the rest.
Set BASIS = 'cc-pVDZ' (and run on a large-RAM machine), or override
BASIS / MEM_BUDGET_GB from the environment, to reproduce the full table.
Results are saved incrementally to qed_ipea_aromatics_results.json so a
partial or killed run is not lost.

Density fitting (QED_IPEA_AUXBASIS) only touches the *AO* stage: it
replaces the dense AO nao^4 integral tensor held on the QED-HF/UHF
reference with a naux*nao^2 3-index factor and speeds the AO->MO
transform. The nso^4 spin-orbital tensor built downstream by QED-GW and
Delta-QED-CCSD -- the wall estimated by peak_gb -- is UNCHANGED, so DF
lowers the peak only by the (secondary) AO term and does not enlarge the
set of molecules this script can run. Use it to shave the AO integral
memory / transform time, not to reach the skipped cc-pVDZ acenes; and
note DF carries a ~mHa error, so the paper-exact rows need auxbasis=None.
=====================================================================
"""
import json
import math
import os

import numpy as np
from pyscf import gto

from OmegaQMC.addons.qed_hf import run_qed_hf
from OmegaQMC.addons.qed_uhf import run_qed_uhf
from OmegaQMC.addons.qed_ccsd import run_qed_ccsd
from OmegaQMC.addons.qed_gw import run_qed_gw

EV = 27.211386245988
OMEGA = 0.415668           # Ha = 11.31 eV (same cavity as the whole table)
MOLECULES = ('benzene', 'naphthalene', 'anthracene')
DO_CCSD = True             # set False to skip the expensive Delta-QED-CCSD

# Small basis for small-RAM machines; 'cc-pVDZ' reproduces the paper.
BASIS = os.environ.get('QED_IPEA_BASIS', 'sto-3g')

# Optional density fitting for the QED-HF / QED-UHF references. Default None
# keeps the exact dense AO integrals (paper-exact). Set QED_IPEA_AUXBASIS to a
# fitting basis (e.g. 'cc-pvdz-jkfit', 'weigend') to build the SCF J/K from the
# 3-index factor and hand the downstream QED-GW / QED-CCSD kernels an 'eri_df'
# reference instead of the dense AO nao^4 tensor. This trims the AO integral
# memory and speeds the AO->MO transform, but does NOT shrink the dominant
# nso^4 spin-orbital tensor those kernels build (see the memory note above), so
# it will not rescue the cc-pVDZ acenes that get skipped. DF also introduces a
# ~mHa approximation error, so leave it None to reproduce the reference table.
AUXBASIS = os.environ.get('QED_IPEA_AUXBASIS') or None


def _total_ram_gb():
    try:
        return (os.sysconf('SC_PAGE_SIZE') * os.sysconf('SC_PHYS_PAGES')
                / 1e9)
    except (ValueError, OSError, AttributeError):
        return 8.0


# A molecule is skipped if its estimated peak working set exceeds this.
MEM_BUDGET_GB = float(os.environ.get(
    'QED_IPEA_MEM_GB', f"{0.70 * _total_ram_gb():.2f}"))


def peak_gb(nao, nelec, auxbasis=None):
    """Rough peak working set (GB) of one run_molecule() call.

    Dominated by the dense nso^4 spin-orbital integral tensor shared by
    the QED-GW and QED-CCSD kernels, plus the dense 2*(Nov+1) photon-
    augmented RPA matrix (built real, then diagonalised into complex
    eigenvectors by scipy.linalg.eig -- the ~4x factor covers that copy
    and the LAPACK workspace). nso = 2*nao spin orbitals.

    The AO two-electron tensor held on the QED-HF/UHF reference is a
    secondary term: dense nao^4 without DF, or a ~4*nao^3 three-index
    factor with density fitting (auxbasis set). It does not change the
    nso^4-dominated wall but is the only term DF affects.
    """
    nso = 2 * nao
    tensor = nso ** 4 * 8 / 1e9
    nov = nelec * (nso - nelec)
    rpa = (2 * (nov + 1)) ** 2 * 8 * 4 / 1e9
    ao = (4 * nao ** 3 if auxbasis else nao ** 4) * 8 / 1e9
    return tensor + rpa + ao


def acene(n_rings, aCC=1.40, aCH=1.09):
    """Idealized planar linear acene, molecular plane = x-z.

    x = long (spine) axis, z = short in-plane axis, y = out-of-plane.
    Returns a pyscf atom list [[symbol, (x, y, z)], ...] (Angstrom).
    """
    ang = np.deg2rad([30, 90, 150, 210, 270, 330])
    cx0 = (n_rings - 1) / 2.0 * math.sqrt(3.0) * aCC
    verts = []
    for k in range(n_rings):
        cx = k * math.sqrt(3.0) * aCC - cx0
        for t in ang:
            verts.append((cx + aCC * math.cos(t), aCC * math.sin(t)))
    uniq = []                                     # dedupe shared bridgeheads
    for v in verts:
        if not any(abs(v[0] - u[0]) < 1e-3 and abs(v[1] - u[1]) < 1e-3
                   for u in uniq):
            uniq.append(v)
    C = np.array(uniq)
    nbr = [[j for j in range(len(C)) if j != i
            and np.linalg.norm(C[i] - C[j]) < 1.2 * aCC]
           for i in range(len(C))]
    atoms = [['C', (float(c[0]), 0.0, float(c[1]))] for c in C]
    for i, c in enumerate(C):
        if len(nbr[i]) == 2:                      # CH carbon -> add H outward
            d = c - C[nbr[i]].mean(axis=0)
            d = d / np.linalg.norm(d)
            h = c + aCH * d
            atoms.append(['H', (float(h[0]), 0.0, float(h[1]))])
    return atoms


GEOMETRIES = {
    'benzene': acene(1),
    'naphthalene': acene(2),
    'anthracene': acene(3),
}


def build(name, charge=0, spin=0):
    return gto.M(atom=GEOMETRIES[name], basis=BASIS, unit='Angstrom',
                 charge=charge, spin=spin, symmetry=False, verbose=0,
                 max_memory=MEM_BUDGET_GB * 1e3)


def run_molecule(name, lam):
    cv = (0.0, 0.0, lam)
    out = {}

    # --- neutral reference ---
    qedhf = run_qed_hf(build(name), OMEGA, cv, verbose=False, tol=1e-12,
                       auxbasis=AUXBASIS)
    homo = qedhf['nocc_spatial'] - 1
    lumo = homo + 1

    # --- self-energy flavours (HOMO -> IP, LUMO -> EA) ---
    g0 = run_qed_gw(qedhf, mode='G0W0', verbose=False)
    ev = run_qed_gw(qedhf, mode='evGW', verbose=False)
    out['koop_IP'] = -g0['eps_HF'][homo] * EV
    out['koop_EA'] = -g0['eps_HF'][lumo] * EV
    out['g0w0_IP'] = -g0['eps_QP'][homo] * EV
    out['g0w0_EA'] = -g0['eps_QP'][lumo] * EV
    out['evgw_IP'] = -ev['eps_QP'][homo] * EV
    out['evgw_EA'] = -ev['eps_QP'][lumo] * EV

    # --- Delta-QED-HF (and optionally Delta-QED-CCSD) ---
    E_N_hf = qedhf['E_qed_hf']
    E_N_cc = None
    if DO_CCSD:
        rn = run_qed_ccsd(qedhf, max_iter=300, verbose=False)
        assert rn['converged'], f"{name} neutral CCSD not converged"
        E_N_cc = rn['E_qed_ccsd_total']

    ion = {}
    for label, charge in (('cation', 1), ('anion', -1)):
        mol_ion = build(name, charge=charge, spin=1)
        try:
            quhf = run_qed_uhf(mol_ion, OMEGA, cv, verbose=False, tol=1e-12,
                               auxbasis=AUXBASIS)
        except RuntimeError:
            quhf = run_qed_uhf(mol_ion, OMEGA, cv, verbose=False,
                               tol=1e-11, damping=0.4, max_iter=4000,
                               auxbasis=AUXBASIS)
        e_hf = quhf['E_qed_uhf']
        e_cc = None
        if DO_CCSD:
            rc = run_qed_ccsd(quhf, max_iter=300, verbose=False)
            assert rc['converged'], f"{name} {label} CCSD not converged"
            e_cc = rc['E_qed_ccsd_total']
        ion[label] = (e_hf, e_cc)

    out['dHF_IP'] = (ion['cation'][0] - E_N_hf) * EV
    out['dHF_EA'] = (E_N_hf - ion['anion'][0]) * EV
    if DO_CCSD:
        out['dCC_IP'] = (ion['cation'][1] - E_N_cc) * EV
        out['dCC_EA'] = (E_N_cc - ion['anion'][1]) * EV
    return out


METHODS = ['koop', 'dHF', 'g0w0', 'evgw', 'dCC']
LABELS = {'koop': 'Koopmans', 'dHF': 'dQED-HF', 'g0w0': 'G0W0',
          'evgw': 'evGW', 'dCC': 'dQED-CCSD'}

if __name__ == '__main__':
    print(f"basis = {BASIS!r},  auxbasis = {AUXBASIS!r} "
          f"({'density-fitted' if AUXBASIS else 'exact'}),  "
          f"memory budget = {MEM_BUDGET_GB:.1f} GB "
          f"(physical RAM ~ {_total_ram_gb():.1f} GB)", flush=True)
    results = {}
    skipped = {}
    for name in MOLECULES:
        est = peak_gb(build(name).nao, build(name).nelectron, auxbasis=AUXBASIS)
        if est > MEM_BUDGET_GB:
            skipped[name] = est
            print(f"... SKIP {name}: est. peak {est:.1f} GB > budget "
                  f"{MEM_BUDGET_GB:.1f} GB (use a smaller BASIS or a "
                  f"larger-RAM machine)", flush=True)
            continue
        for lam in (0.0, 0.05):
            key = f"{name}|{BASIS}|{lam:.2f}"
            print(f"... running {key} (est. peak {est:.1f} GB)", flush=True)
            results[key] = run_molecule(name, lam)
            with open('qed_ipea_aromatics_results.json', 'w') as fh:
                json.dump(results, fh, indent=1)

    if skipped:
        print("\nskipped (over memory budget): "
              + ", ".join(f"{n} (~{g:.0f} GB)" for n, g in skipped.items()))

    for quantity in ('IP', 'EA'):
        print("\n" + "=" * 78)
        print(f"Vertical {quantity} (eV), omega_cav = {OMEGA} Ha, {BASIS}")
        print("=" * 78)
        print(f"{'system':>16} {'lam':>5}"
              + ''.join(f"{LABELS[m]:>11}" for m in METHODS))
        for key, row in results.items():
            name, basis, lam = key.split('|')
            cells = ''.join(
                f"{row[f'{m}_{quantity}']:11.3f}"
                if f'{m}_{quantity}' in row else f"{'---':>11}"
                for m in METHODS)
            print(f"{name:>16} {lam:>5}" + cells)
