#!/usr/bin/env python
"""Generate the rs-scan YAMLs at N=50 (commensurate triangular WC).

Writes 16 YAMLs into inputs/2dheg/rs_scan_n50/ — one fluid + one
crystal per rs.  Light symmetric ansatz (emb=32, n_det=1, no
backflow / Jastrow / ghost; Kato cusp on).  Crystal eval mc_timestep
scaled with rs^2 to keep step ~ sigma/3 across the scan.

Usage:  python scripts/gen_rs_scan_yamls.py
"""
import os
from pathlib import Path

RS_VALUES = [60, 50, 45, 40, 38, 35, 30, 20]   # high to low density
N = 50
OUT_DIR = Path('inputs/2dheg/rs_scan_n50')

# Crystal eval mc_timestep scales as (rs/50)^2; baseline 5.0 at rs=50.
def crystal_eval_dt(rs):
    return 5.0 * (rs / 50.0) ** 2


def fluid_yaml(rs):
    project = f'rs_scan_n50_rs{rs}_fluid'
    return f'''# rs scan, N=50, fluid sector @ rs={rs}.
# Auto-generated by scripts/gen_rs_scan_yamls.py.

project: {project}

system:
  dim: 2
  rs: {float(rs)}
  N: {N}
  polarization: unpolarized

ansatz:
  type: psiformer
  embedding_dim: 32
  layers: 1
  heads: 2
  two_particle_dim: 16
  n_det: 1
  full_determinant: false
  use_cusp: true
  deep_jastrow: false
  pair_jastrow: false
  use_backflow: false
  use_ghost_atom: false
  envelope_type: plane_wave
  n_virt_pw: 8
  det_jitter: 0.0

pretrain:
  iters: 0

optimize:
  type: sr
  iters: 5000
  walkers: 256
  lr: 0.05
  var_weight: 0.0
  mcmc_decorr_steps: 30
  mc_timestep: 0.1
  sr_damping: 1.0e-3
  sr_n_cg: 15

eval:
  walkers: 256
  blocks: 30
  equil_blocks: 15
  steps_per_block: 20

observables:
  enabled: true
  triangular_shells: 2
  cartesian_n_max: 6
  n_walkers: 256
  equil_steps: 200
  sample_steps: 80
  decorr_steps: 5

twist:
  n_twists: 0

ewald:
  n_real: 4
  n_recip: 8
'''


def crystal_yaml(rs):
    project = f'rs_scan_n50_rs{rs}_crystal'
    eval_dt = crystal_eval_dt(rs)
    return f'''# rs scan, N=50, crystal sector @ rs={rs}.
# Auto-generated by scripts/gen_rs_scan_yamls.py.

project: {project}

system:
  dim: 2
  rs: {float(rs)}
  N: {N}
  polarization: unpolarized

ansatz:
  type: psiformer
  embedding_dim: 32
  layers: 1
  heads: 2
  two_particle_dim: 16
  n_det: 1
  full_determinant: false
  use_cusp: true
  deep_jastrow: false
  pair_jastrow: false
  use_backflow: false
  use_ghost_atom: false
  envelope_type: crystal_gaussian
  crystal_sigma_init: 0.10
  crystal_spin_pattern: neel
  crystal_det_jitter: 0.0

pretrain:
  iters: 0

optimize:
  type: sr
  iters: 5000
  walkers: 256
  lr: 0.05
  var_weight: 0.0
  mcmc_decorr_steps: 30
  mc_timestep: 0.025
  sr_damping: 1.0e-3
  sr_n_cg: 15

eval:
  walkers: 256
  blocks: 30
  equil_blocks: 20
  steps_per_block: 20
  mc_timestep: {eval_dt:.3f}        # rs-dependent: ~ (rs/50)^2 * 5

observables:
  enabled: true
  triangular_shells: 2
  cartesian_n_max: 6
  n_walkers: 256
  equil_steps: 200
  sample_steps: 80
  decorr_steps: 5

twist:
  n_twists: 0

ewald:
  n_real: 4
  n_recip: 8
'''


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for rs in RS_VALUES:
        f = OUT_DIR / f'rs_scan_n50_rs{rs}_fluid.yaml'
        f.write_text(fluid_yaml(rs))
        c = OUT_DIR / f'rs_scan_n50_rs{rs}_crystal.yaml'
        c.write_text(crystal_yaml(rs))
        print(f'  wrote {f.name}, {c.name}')
    print(f'\n{len(RS_VALUES) * 2} YAMLs in {OUT_DIR}/')


if __name__ == '__main__':
    main()
